inherit_gem:
  rubocop-config-umbrellio: lib/rubocop.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/*

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/LineLength:
  Max: 100
