# frozen_string_literal: true

source 'https://rubygems.org'

# Future
# gem 'pg'
gem 'puma'
gem 'rack-cors'
gem 'rails', '~> 5.1.4'
# Prototype
gem 'sqlite3'
gem 'surrealist'

group :development, :test do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'pry'
  gem 'rspec'
  gem 'rubocop'
  gem 'rubocop-config-umbrellio'
end
